### PR TITLE
Fix feat easing type

### PR DESCRIPTION
**Pull request by DirectuX**
reply to [this request](https://github.com/petrSchreiber/BetweenTheBubbles-tb/pull/5#discussion_r352374782)

### CODE REVIEW

**Review by petrSchreiber — APPROVED** [review]
Excellent, may I merge?

**Comment by DirectuX** [comment]
no no , look [at this](https://github.com/petrSchreiber/BetweenTheBubbles-tb/pull/5#issue-347090255) first. I have to understand why _Fix feat easing type_ is not working as wanted. [ Feat_easingType](https://github.com/petrSchreiber/BetweenTheBubbles-tb/tree/feat_easingType) is the working branch

**Comment by petrSchreiber** [comment]
I see, thank you

**Comment by DirectuX** [comment]
If it's ok for you we can delete this branch. In conclusion the "maybe not useful" part is not useful. Will remove on next real fix or feat_edit.

**Comment by DirectuX** [comment]
If it's ok for you we can delete this branch. In conclusion the "maybe not useful" part is not useful. Will remove on next real fix or feat_edit.

**Comment by petrSchreiber** [comment]
Okay, I will delete the branch now. Thanks!

**Pull request closed without merging**
